[phases.setup]
nixPkgs = ['nginx', 'php82', 'php82Extensions.mysqli', 'php82Extensions.curl', 'php82Extensions.gd']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[start]
cmd = 'nginx -c /app/nginx.conf'